### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Martinvdm** [vloris/home-assistant#2]
Getting the following error:
```
Traceback (most recent call last):,
  File "/usr/src/app/homeassistant/helpers/entity.py", line 249, in async_update_ha_state,
    await self.async_device_update(),
  File "/usr/src/app/homeassistant/helpers/entity.py", line 419, in async_device_update,
    await self.hass.async_add_executor_job(self.update),
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run,
    result = self.fn(*self.args, **self.kwargs),
  File "/config/custom_components/twentemilieu/sensor.py", line 230, in update,
    self._reader.update(),
  File "/config/custom_components/twentemilieu/sensor.py", line 130, in update,
    address_id = self._find_unique_address_id(),
  File "/config/custom_components/twentemilieu/sensor.py", line 155, in _find_unique_address_id,
    response = self._do_post_request('FetchAdress', data),
  File "/config/custom_components/twentemilieu/sensor.py", line 146, in _do_post_request,
    url, headers=self._request_headers, data=data).json(),
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json,
    return complexjson.loads(self.text, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads,
    return _default_decoder.decode(s),
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode,
    obj, end = self.raw_decode(s),
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode,
    return self.scan_once(s, idx=_w(s, idx).end()),
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Do you have issues with it?

**Comment by floriskruisselbrink** [comment]
Hi! Thanks for using my code! And sorry for the delayed response to your question.
No, I never had such issues, it was working fine. 
Last week I upgraded home-assistent to the (then) latest release 0.99.3 which has a builtin 'twentemilieu' component, so by now I stopped using the custom one.
I changed the automations and sensors a little bit (see packages/twentemilieu.yaml) because the builtin component doesn't have sensors for today and tomorrow's pickup.

I suggest you try the same: see https://www.home-assistant.io/integrations/twentemilieu/ for more information
